### ISSUE TITLE
Unknown module

### ISSUE THREAD

**Issue by pepe** [dankamongmen/bowlsofwrath#1]
Hello, when I try to render `dankbowl.scad` I am getting:

```
WARNING: Ignoring unknown module 'roundedcube' in file dankbowl.scad, line 65
```

The `roundcube` model should be added to the repository. I would also mention the use of the BOSL2 in the readme.

**Comment by dankamongmen** [comment]
wow, was not expecting people to look at this project. neat =]

**Comment by pepe** [comment]
I love your work. Thank you for the fix.
